name: task-management

services:
  frontend:
    container_name: task-management-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - task-management-network

networks:
  task-management-network:
    name: task-management-network 